### ISSUE TITLE
iasnecrypt module

### ISSUE THREAD

**Issue by MAndrewSprong** [The-Fireplace/In-Game-Account-Switcher#3]
the module the_fireplace.iasencrypt and contained class is missing from repository.

**Comment by The-Fireplace** [comment]
This is intentional. Making it public would be a security risk.

**Comment by MAndrewSprong** [comment]
Then I will have to roll my own. Or in lieu of that, get a build for 1.10.2 which is my goal, because I am tired of the invalid credentials error, that happens randomly due to poor authentication at the launcher level.

**Comment by The-Fireplace** [comment]
What do you mean, get a build for 1.10.2? 6.1.2 is built for 1.10.2. This invalid credentials error you mentioned, I will look in to and see if I can reproduce it.

**Comment by MAndrewSprong** [comment]
Where can I get 6.1.2? - I tried searching for it to no avail.

**Comment by MAndrewSprong** [comment]
Nevermind, I found it on curse. Thank you for your efforts and mod.

**Comment by The-Fireplace** [comment]
No problem. If you continue to have issues, please let me know so I can work to fix them.
