### ISSUE TITLE
[1.11] [IAS-1.11.2-7.0.1] Only works in 1.11.2  and not in 1.11

### ISSUE THREAD

**Issue by shortybsd** [The-Fireplace/In-Game-Account-Switcher#8]
Forge version 2199
MC version 1.11
InGameAccountSwitcher-Forge-1.11.2-7.0.1 
IAS is missing backward-compatibility for 1.11, it only works in 1.11.2. It is listed on site that it works with 1.11.
It ignored this line that is if this was in the source at compile time. I did notice that code is for 702 version.
https://github.com/The-Fireplace/In-Game-Account-Switcher/blob/master/build.gradle#L95

**Comment by The-Fireplace** [comment]
All that line does is signals CurseForge that it works on 1.11. I will unmark that file as 1.11-supporting, and the next one for 1.11.2 actually will support 1.11.

**Comment by shortybsd** [comment]
Very nice, thank you sir. Gotcha, yeah in my mods it is under reference example:
`public static final String ACCEPTED_VERSIONS= "[1.11]";`

**Comment by The-Fireplace** [comment]
Only reason it didn't accept 1.11 was because the Minecraft version in
mcmod.info was set to 1.11.2. I swear at one point in time, Forge didn't
enforce it when it was set in mcmod.info, but apparently it does now.

**Comment by shortybsd** [comment]
The fix has nothing to do with your mcmod.info you can just use $mcversion in there. The main thing in your class you can use this for an example acceptedMinecraftVersions = "[1.10,1.11)"
Note that right parenthesis lets any versions 1.10.x thru 1.11.x work. Example If they made a 1.11.99 it would allow/accept it. Tested and worked great. =D
